apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloservice
  namespace: prometheus-qg-quality-gate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloservice
  template:
    metadata:
      labels:
        app: helloservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gabrieltanner/hello-server:v0.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: PORT
          value: "9000"
