---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.keptn.service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.keptn.service }}
  template:
    metadata:
      labels:
        app: {{ .Values.keptn.service }}
        app.kubernetes.io/name: "{{ .Values.keptn.service }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: "{{ .Values.keptn.project }}"
        app.kubernetes.io/managed-by: Keptn
        app.kubernetes.io/version: {{ (split ":" .Values.image)._1 | default "latest" }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    spec:
      containers:
      - name: {{ .Values.keptn.service }}
        image: "{{ .Values.image }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          protocol: TCP
          containerPort: {{ .Values.service.targetPort }}
        env:
# Following DT_CLUSTER_ID would "hard code" the PGI naming which we will do through a naming rule using the meta data on this container
#        - name: DT_CLUSTER_ID
#          value: "{{ .Values.keptn.project }}.{{ .Values.keptn.service }}.{{ .Values.keptn.stage }}.{{ .Values.keptn.deployment }}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: "metadata.name"
        - name: DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: "metadata.labels['deployment']"
        - name: DT_RELEASE_VERSION
          valueFrom:
            fieldRef:
              fieldPath: "metadata.labels['app.kubernetes.io/version']"
        - name: DT_RELEASE_PRODUCT
          value: "{{ .Values.keptn.project }}"
        - name: DT_RELEASE_STAGE
          value: "{{ .Values.keptn.stage }}"
        - name: CONTAINER_IMAGE
          value: "{{ .Values.image }}"
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 15
        resources:
          limits:
            cpu: 50m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi