#deploymentURIsLocal:
#  - "<my-local-url>" # e.g. http://my-service.sockshop-dev:8080
deploymentURIsPublic:
  - "http://tnt-XXX-svc.REPLACE_KEPTN_PROJECT-production.REPLACE_KEPTN_PRODUCTION_INGRESS:80/"